[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

board_build.partitions = huge_app.csv

lib_deps =
    Wire
    WiFi
    ArduinoJson
    https://github.com/rfetick/MPU6050_light
    ESP32 BLE Arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0
